config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_university.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_university/urls.py
from django.urls import path
from . import views

app_name = 'crm_university'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('faculty/list/', views.faculty, name='faculty_list'),
    path('group/list/', views.group, name='group_list'),
    path('department/list/', views.department, name='department_list'),
    path('student/list/', views.student, name='student_list'),
    path('subject/list/', views.subject, name='subject_list'),
    path('teacher/list/', views.teacher, name='teacher_list'),
    path('faculty/create/', views.faculty_form, name='faculty_create'),
    path('group/create/', views.group_form, name='group_create'),
    path('department/create/', views.department_form, name='department_create'),
    path('student/create/', views.student_form, name='student_create'),
    path('subject/create/', views.subject_form, name='subject_create'),
    path('teacher/create/', views.teacher_form, name='teacher_create'),
    path('update/faculty/<int:pk>/', views.update_faculty, name='faculty_update'),
    path('update/group/<int:pk>/', views.update_group, name='group_update'),
    path('update/department/<int:pk>/', views.update_department, name='department_update'),
    path('update/student/<int:pk>/', views.update_student, name='student_update'),
    path('update/subject/<int:pk>/', views.update_subject, name='subject_update'),
    path('update/teacher/<int:pk>/', views.update_teacher, name='teacher_update'),
    path('delete/faculty/<int:pk>/', views.delete_faculty, name='faculty_delete'),
    path('delete/group/<int:pk>/', views.delete_group, name='group_delete'),
    path('delete/department/<int:pk>/', views.delete_department, name='department_delete'),
    path('delete/student/<int:pk>/', views.delete_student, name='student_delete'),
    path('delete/subject/<int:pk>/', views.delete_subject, name='subject_delete'),
    path('delete/teacher/<int:pk>/', views.delete_teacher, name='teacher_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!-- Fontfaces CSS-->
    <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/animsition/animsition.min.css'%}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- MENU SIDEBAR -->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <!-- Replace with your logo image -->
                    <img src="{% static 'images/icon/logo.png' %}" alt="Cool Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li class="active">
                            <a href="{% url 'crm_university:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:faculty_list' %}"><i class="fas fa-chart-bar"></i>Faculty</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:department_list' %}"><i class="fas fa-chart-bar"></i>Department</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:subject_list' %}"><i class="fas fa-chart-bar"></i>Subject</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:teacher_list' %}"><i class="fas fa-chart-bar"></i>Teacher</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:group_list' %}"><i class="fas fa-chart-bar"></i>Group</a>
                        </li>
                        <li>
                            <a href="{% url 'crm_university:student_list' %}"><i class="fas fa-chart-bar"></i>Student</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR -->
        <div class="page-container">
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="{% static 'images/icon/avatar-01.jpg' %}" alt="John Doe" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">John Doe</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="{% static 'images/icon/avatar-01.jpg' %}" alt="John Doe" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">John Doe</a>
                                                    </h5>
                                                    <span class="email">johndoe@example.com</span>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-account"></i>Account</a>
                                                </div>
                                                <div class="account-dropdown__item">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-settings"></i>Setting</a>
                                                </div>
                                                <div class="account-dropdown__item">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-money-box"></i>Billing</a>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="{% url 'users:logout' %}">
                                                    <i class="zmdi zmdi-power"></i>Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            {% block content %}{% endblock %}

 <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'js/main.js' %}"></script>
        </div>
    </div>
</body>
</html>

templates/confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!-- Fontfaces CSS-->
    <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

<style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style><link type="text/css" rel="stylesheet" charset="UTF-8" href="https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.26tY-h6gH9w.L.W.O/am=YDA/d=0/rs=AN8SPfo2purg3MUBXTtjVeO_sPDrV4tGQA/m=el_main_css"></head>
<body class="animsition" style="animation-duration: 900ms; opacity: 1;">
    <div class="page-wrapper">
        <!-- MENU SIDEBAR -->

<aside class="menu-sidebar d-none d-lg-block">
    <div class="logo">
        <a href="#">
            <!-- Replace with your logo image -->
            <img src="{% static 'images/icon/logo.png' %}" alt="Крутой Админ">
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1 ps">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li class="active">
                        <a href="{% url 'crm_university:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:faculty_list' %}"><i class="fas fa-chart-bar"></i>Faculty</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:department_list' %}"><i class="fas fa-chart-bar"></i>Department</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:subject_list' %}"><i class="fas fa-chart-bar"></i>Subject</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:teacher_list' %}"><i class="fas fa-chart-bar"></i>Teacher</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:group_list' %}"><i class="fas fa-chart-bar"></i>Group</a>
                    </li>
                    <li>
                        <a href="{% url 'crm_university:student_list' %}"><i class="fas fa-chart-bar"></i>Student</a>
                    </li>
            </ul>
        </nav>
    <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
</aside>
        <!-- END MENU SIDEBAR -->
        <div class="page-container">
            <!-- Include the user bar -->

<header class="header-desktop">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="header-wrap">
                <div class="header-button">
                    <div class="account-wrap">
                        <div class="account-item clearfix js-item-menu">
                            <div class="image">
                                <img src="{% static 'images/icon/avatar-01.jpg' %}" alt="John Doe">
                            </div>
                            <div class="content">
                                <a class="js-acc-btn" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">John Doe</font></font></a>
                            </div>
                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    <div class="image">
                                        <a href="#">
                                            <img src="{% static 'images/icon/avatar-01.jpg' %}" alt="John Doe">
                                        </a>
                                    </div>
                                    <div class="content">
                                        <h5 class="name">
                                            <a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">John Doe</font></font></a>
                                        </h5>
                                        <span class="email"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">johndoe@example.com</font></font></span>
                                    </div>
                                </div>
                                <div class="account-dropdown__body">
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-account"></i>Account</a>
                                    </div>
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-settings"></i>Setting</a>
                                    </div>
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-money-box"></i>Billing</a>
                                    </div>
                                </div>
                                <div class="account-dropdown__footer">
                                    <a href="{% url 'users:logout' %}">
                                        <i class="zmdi zmdi-power"></i>Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

            <!-- HEADER DESKTOP-->
            <!-- MAIN CONTENT-->

<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="overview-wrap">
                        <h2 class="title-1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Are you sure to delete this
                            {% if g %}
                                "{{ group.name }}"?
                            {% elif d %}
                                "{{ department.name }}"?
                            {% elif s %}
                                "{{ student.last_name }}&emsp;{{ student.first_name }}"?
                            {% elif su %}
                                "{{ subject.name }}"?
                            {% elif teacher %}
                                "{{ teacher.last_name }}&emsp;{{ teacher.first_name }}"?
                            {% else %}
                                "{{ faculty.name }}"?
                            {% endif %}
                        </font></font></h2>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Confirmation of the department of the
                                {% if g %}
                                    group
                                {% elif d %}
                                    department
                                {% elif s %}
                                    student
                                {% elif su %}
                                    subject
                                {% elif teacher %}
                                    teacher
                                {% else %}
                                    faculty
                                {% endif %}
                            </font></font></strong>
                        </div>
                        <div class="card-body card-block">
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-md mr-2"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yes,I'm sure</font></font></button>
                                <a href="../" class="btn btn-secondary btn-md"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">No,take me back</font></font></a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'js/main.js' %}"></script>
        </div>
    </div>
</body>
</html>

templates/faculty_form.html
{% extends 'base.html' %}


{% block content %}
            <!-- HEADER DESKTOP-->
        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="overview-wrap">
                                <h2 class="title-1">
                                    {% if g %}
                                        Update {{ g.name }}
                                    {% elif d %}
                                        Update {{ d.name }}
                                    {% elif s %}
                                        Update {{ s.last_name }}&emsp;{{ s.first_name }}
                                    {% elif su %}
                                        Update {{ su.name }}
                                    {% elif t %}
                                        Update {{ s.last_name }}&emsp;{{ s.first_name }}
                                    {% elif f %}
                                        Update {{ f.name }}
                                    {% else %}
                                        Add
                                    {% endif %}
                                </h2>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <strong>
                                        {% if g %}Group
                                        {% elif d %}Department
                                        {% elif s %}Student
                                        {% elif su %}Subject
                                        {% elif t %}Teacher
                                        {% else %}Faculty
                                        {% endif %}
                                    </strong>
                                    <small>Form</small>
                                </div>
                                <div class="card-body card-block">
                                    <form method="post">
                                        <div class="form-group">
                                            {% csrf_token %}
                                            {{ forms.as_p }}
                                        </div>

                                        <button type="submit" class="btn btn-success btn-md">
                                            {% if f %}
                                                Update
                                            {% elif g %}
                                                Update
                                            {% elif d %}
                                                Update
                                            {% elif s %}
                                                Update
                                            {% elif su %}
                                                Update
                                            {% elif t %}
                                                Update
                                            {% else %}
                                                Add
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT-->

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                        <img src="{% static 'images/icon/logo.png' %}" alt="Cool Admin" />
                        <h2>Login</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">login</button>
                        </form>
                        <br>
                        <a href="{% url 'users:register' %}">Create an account</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create account</title>
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                        <img src="{% static 'images/icon/logo.png' %}" alt="Cool Admin" />
                        <h2>Create account</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create</button>
                        </form>
                        <br>
                        <a href="{% url 'users:login' %}">You have an account</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>